module.exports = {
  UserController: require("./UserController"),
  LogController: require("./LogController"),
  UserEventLogController: require("./UserEventLogController"),
  UserVerifyRequestController: require("./UserVerifyRequestController"),
  SystemController: require("./SystemController"),
  ListingCategoriesController: require("./ListingCategoriesController"),
  ListingDefectController: require("./ListingDefectController"),
  SearchedWordController: require("./SearchedWordController"),
  ListingController: require("./ListingController"),
  ListingApprovalRequestController: require("./ListingApprovalRequestController"),
  MainController: require("./MainController"),
  ListingCategoryCreateNotificationController: require("./ListingCategoryCreateNotificationController"),
  OrderController: require("./OrderController"),
  OrderUpdateRequestController: require("./OrderUpdateRequestController"),
  SenderPaymentController: require("./SenderPaymentController"),
  RecipientPaymentController: require("./RecipientPaymentController"),
  ListingDefectQuestionController: require("./ListingDefectQuestionController"),
  ListingCommentController: require("./ListingCommentController"),
  OwnerCommentController: require("./OwnerCommentController"),
  TenantCommentController: require("./TenantCommentController"),
  DisputeController: require("./DisputeController"),
  ChatController: require("./ChatController"),
};
