module.exports = {
  userApiRoutes: require("./userRoutes"),
  authApiRoutes: require("./authRoutes"),
  logApiRoutes: require("./logRoutes"),
  userVerifyRequestApiRoutes: require("./userVerifyRequestRoutes"),
  userEventLogApiRoutes: require("./userEventLogRoutes"),
  systemApiRoutes: require("./systemRoutes"),
  listingCategoryRoutes: require("./listingCategoryRoutes"),
  listingDefectRoutes: require("./listingDefectRoutes"),
  searchedWordsRoutes: require("./searchedWordsRoutes"),
  listingRoutes: require("./listingRoutes"),
  orderRoutes: require("./orderRoutes"),
  orderUpdateRequestRoutes: require("./orderUpdateRequestRoutes"),
  listingApprovalRequestRoutes: require("./listingApprovalRequestRoutes"),
  listingCategoryCreateNotificationRoutes: require("./listingCategoryCreateNotificationRoutes"),
  mainRoutes: require("./mainRoutes"),
  senderPaymentRoutes: require("./senderPaymentRoutes"),
  recipientPaymentRoutes: require("./recipientPaymentRoutes"),
  listingDefectQuestionRoutes: require("./listingDefectQuestionRoutes"),
};
