module.exports = {
  userRoutes: require("./userRoutes"),
  authRoutes: require("./authRoutes"),
  logRoutes: require("./logRoutes"),
  userVerifyRequestRoutes: require("./userVerifyRequestRoutes"),
  userEventLogRoutes: require("./userEventLogRoutes"),
  systemRoutes: require("./systemRoutes"),
  listingCategoryRoutes: require("./listingCategoryRoutes"),
  searchedWordsRoutes: require("./searchedWordsRoutes"),
  listingRoutes: require("./listingRoutes"),
  orderRoutes: require("./orderRoutes"),
  orderUpdateRequestRoutes: require("./orderUpdateRequestRoutes"),
  listingApprovalRequestRoutes: require("./listingApprovalRequestRoutes"),
  listingCategoryCreateNotificationRoutes: require("./listingCategoryCreateNotificationRoutes"),
  mainRoutes: require("./mainRoutes"),
  senderPaymentRoutes: require("./senderPaymentRoutes"),
  recipientPaymentRoutes: require("./recipientPaymentRoutes"),
  commentRoutes: require("./commentRoutes"),
  disputeRoutes: require("./disputeRoutes"),
  chatRoutes: require("./chatRoutes"),
};
